configure:
  languages:
    go: true
  plugins:
    - .aspect/cli/shell.star
    - .aspect/cli/go_image.star
lint:
  aspects:
    - //tools/lint:linters.bzl%shellcheck

plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0
