load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "algo",
    srcs = ["ubuntu20_4k8s.go"],
    importpath = "github.com/cohesity/cluster-api-provider-bringyourownhost/installer/internal/algo",
    visibility = ["//installer:__subpackages__"],
)
