# golangci.com configuration
# https://golangci-lint.run/usage/configuration/
version: "2"
run:
  allow-parallel-runners: true
  timeout: 10m
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - copyloopvar
    - dupl
    - dupword
    - errcheck
    - err113
    - funlen
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    # - nolintlint
    - rowserrcheck
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

  # don't enable:
  disable:
    - asciicheck
    - exhaustive
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - lll
    - nestif
    - prealloc
    - revive
    - wsl
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goheader:
      values:
        const:
          COMPANY: Cohesity, Inc.
          LICENSE: Apache-2.0
        regexp:
          YEAR: 20\d*-*\d*
      template: |-
        Copyright {{ YEAR }} {{ COMPANY }} All Rights Reserved.
        SPDX-License-Identifier: {{ LICENSE }}
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-functions:
        - log.*
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
    whitespace:
      multi-func: true
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - path: api/*
        linters:
          - lll
      - path: internal/*
        linters:
          - dupl
          - lll
      - path: _test\.go
        linters:
          - dupl
          - gosec
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true
    goimports:
      local-prefixes:
        - github.com/cohesity
    gofumpt:
      extra-rules: false # don't enable extra rules, which are not in gofumpt by default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new: true