comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes

#list of paths (folders or file names) to exclude files from being collected by Codecov
ignore:
- "test"
- "internal/controller/infrastructure/byohost_controller.go"
- "internal/controller/infrastructure/byomachinetemplate_controller.go"
- "api/infrastructure/v1beta1/*_types.go"
- "api/infrastructure/v1beta1/zz_generated.deepcopy.go"
