load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "build-bundle",
    srcs = ["build-bundle.sh"],
)

sh_binary(
    name = "build-push-bundle",
    srcs = ["build-push-bundle.sh"],
)

sh_binary(
    name = "push-bundle",
    srcs = ["push-bundle.sh"],
)
