load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "version",
    srcs = [
        "doc.go",
        "version.go",
    ],
    importpath = "github.com/cohesity/cluster-api-provider-bringyourownhost/agent/version",
    visibility = ["//visibility:public"],
)
