load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "ensure-kustomize",
    srcs = ["ensure-kustomize.sh"],
)

sh_binary(
    name = "getting_started",
    srcs = ["getting_started.sh"],
)

sh_binary(
    name = "install-host-agent-service",
    srcs = ["install-host-agent-service.sh"],
)

sh_binary(
    name = "version",
    srcs = ["version.sh"],
)
