load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = ["utils.go"],
    importpath = "github.com/cohesity/cluster-api-provider-bringyourownhost/common",
    visibility = ["//visibility:public"],
    deps = ["@com_github_pkg_errors//:errors"],
)
