load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "events",
    srcs = ["testutils.go"],
    importpath = "github.com/cohesity/cluster-api-provider-bringyourownhost/test/utils/events",
    visibility = ["//visibility:public"],
)
