name: Check Markdown links

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@master
      - uses: tcort/github-action-markdown-link-check@ef7e09486e579ba7479700b386e7ca90f34cbd0a # v3.13.7
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"
          base-branch: "main"
          config-file: ".github/workflows/markdown.links.config.json"
