name: Draft Release

on:
  push:
    # Build and publish artifacts when new tag is created for release
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-controller
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Setup Bazel environment
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: LLogin to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses docker/metadata-action to extract tags and labels that will be applied to the specified image.
      # The id "meta" allows the output of this step to be referenced in a subsequent step.
      # The images value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Build Release Artifacts
        run: IMG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}" make build-release-artifacts

      # ========================================================
      # Add a step to generate the provenance subjects as shown below.
      # Update the sha256 sum arguments to include all binaries that you generate provenance for.
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls _dist/*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release

  release:
    needs: [build, provenance]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Publish Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          draft: true
          generate_release_notes: true
          files: |
            _dist/byoh-hostagent-linux-amd64
            _dist/cluster-template.yaml
            _dist/cluster-template-topology.yaml
            _dist/clusterclass-quickstart.yaml
            _dist/cluster-template-docker.yaml
            _dist/cluster-template-topology-docker.yaml
            _dist/clusterclass-quickstart-docker.yaml
            _dist/infrastructure-components.yaml
            _dist/metadata.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
