name: "Merge on lgtm label"
on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: jpmcb/prow-github-actions@c44ac3a57d67639e39e4a4988b52049ef45b80dd # v2.0.0
        with:
          jobs: "lgtm"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "squash"
