name: golangci-lint

on:
  push:
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "LICENSE"
      - "NOTICE"
      - "PROJECT"
      - "SECURITY_CONTACTS"
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "LICENSE"
      - "NOTICE"
      - "PROJECT"
      - "SECURITY_CONTACTS"

jobs:
  golangci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go 1.24.3
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          only-new-issues: true
