# Automatically label new pull requests based on the paths of files being changed
name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - name: Label pull requests based on the file paths
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml
