name: E2E Tests

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "LICENSE"
      - "NOTICE"
      - "PROJECT"
      - "SECURITY_CONTACTS"

jobs:
  e2e-pr-blocking:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: turn off swap
        run: sudo swapoff -a

      - name: Set netfilter conntrack max
        run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

      - name: Run Cluster Class e2e tests
        run: yes | GINKGO_FOCUS="\[Cluster-Class\]" make test-e2e

      - name: Run PR-Blocking e2e tests
        run: yes | GINKGO_FOCUS="\[PR-Blocking\]" make test-e2e
